baseURL: https://www.gerardchung.com
languageCode: en-us
title: Gerard Chung
theme: avicenna
googleAnalytics: UA-1234-6
timeout: 3000
params:
  affilation:
    - contact: gerard@nus.edu.sg
      name: Social Service Research Centre, NUS
      position: Research Fellow
  #twitter: @GerardChung
  #blog: 'www.gerardchung.com'
  cv_name: cv.pdf
  interests: 'Parenting, Family Services, Intervention research, Evaluation, Administrative data, Risk assessment, Text-as-data analysis, Computational social science'
  introduction:
    paragraph:
      - text: "I am a research fellow at the [Social Service Research Centre](https://fass.nus.edu.sg/ssr/), National University of Singapore. I have a Ph.D. in social work from the University of 
               North Carolina at Chapel Hill [School of Social Work](https://ssw.unc.edu/). I had also practiced as a social worker in a family service centre in Singapore.\n   "
      - text: "As a social work researcher, I am interested in researching parenting, family services in the community, and risk assessment. I am especially interested in intervention research and in the use of administrative data to improve social work processes.
               I also identify as a methodologist where the through
               line connecting my research interests involved the use of computational
               social science methods and advanced statistical methods.\n\ "
#      - text: "My scholarly work can be accessed at  __[Google Scholar](https://scholar.google.com/citations?user=9aeYOx8AAAAJ&hl=en)__ --
#                __[ResearchGate](https://www.researchgate.net/profile/Gerard-Chung)__ -- __[GitHub](https://github.com/gerardchung)__ \n\ "
      - text: "My scholarly work can be accessed at [Google Scholar](https://scholar.google.com/citations?user=9aeYOx8AAAAJ&hl=en) --
                [ResearchGate](https://www.researchgate.net/profile/Gerard-Chung) -- [GitHub](https://github.com/gerardchung) \n\ "
              
  projects:
    - project:
        - blog_link: ''
          code_link: 'https://github.com/gerardchung/ssa_covid_news'
          description: Analysis of 1,095 news articles using a corpus linguistic approach 
          name: News Media Representations of Social Service Agencies During COVID-19 in Singapore
          project_page: 'https://gerardchung.github.io/ssanews/'
          
        - blog_link: ''
          code_link: 'https://github.com/gerardchung/social_work_news_singapore'
          description: Text data analysis of 7000 news articles related to Social Work Profession in Singapore
          name: Text-mining news on Social Work Profession in Singapore
          project_page: 'https://github.com/gerardchung/social_work_news_singapore'


        - blog_link: ''
          code_link: ''
          description: Narratives of Directors' messages from 2017 to 2021
          name: Annual reports of Social Service Agencies in Singapore 
          project_page: 'https://github.com/gerardchung/ssa_annual_reports'

        - blog_link: ''
          code_link: ''
          description: A survey study of parenting during COVID-19 pandemic in Singapore
          name: Parenting During COVID-19 in Singapore
          project_page: 'http://sgcovidparenting.mystrikingly.com/'
          
        - blog_link: ''
          code_link: ''
          description: Preliminary results of meta-analysis in interactive table 
          name: Meta-analysis of Risk Factors of Child Maltreatment Recurrence
          project_page: 'https://gerardchung.shinyapps.io/shiny_metaanalysis_effects/'
          
        - blog_link: ''
          code_link: 'https://github.com/gerardchung/riskfactors_chmaltreatment'
          description: Use PRM to identify a set of risk factors that have strong predictive relationship with child maltreatment recurrence outcome in the NSCAW data.
          name: Predictive Risk Modeling of Risk Factors of Child Maltreatment Re-reports
          project_page: 'https://github.com/gerardchung/riskfactors_chmaltreatment'
          
 
  publications:
    - paper:
    
        - authors: __Gerard Chung__, Maria Rodriguez, Paul Lanier, Daniel Gibbs
          blog_link: ''
          code_link: ''
          dest: Journal of Technology in Human Services (Accepted for publication)
          link: https://doi.org/10.31219/osf.io/enzst
          name: "Text-mining open-ended survey responses using structural topic modeling: A practical demonstration to understand parents' coping methods during the COVID-19 pandemic in Singapore"


        - authors: __Gerard Chung__, Kirsten Kain, Sarah Rabiner Eisensmith, Paul Lanier 
          blog_link: ''
          code_link: ''
          dest: Journal of Child And Family Studies
          link:  https://doi.org/10.1007/s10826-022-02227-y
          name: "Effects of Youth Educational Aspirations on Academic Outcomes and Racial Differences: A Propensity Score Matching Approach"
      year: 2022
    
    - paper:
    
        - authors: __Gerard Chung__, Paul Lanier, Chen Ding-Chen
          blog_link: ''
          code_link: ''
          dest: Child & Family Social Work
          link:  https://doi.org/10.1111/cfs.12866
          name: "What predicts mothers' use of spanking in the first 6 years of early childhood? A latent growth curve analysis"
    
        - authors: __Gerard Chung__, David Ansong, Kanisha Brevard, Chen Ding-Chen
          blog_link: ''
          code_link: ''
          dest: Child Abuse & Neglect 
          link: https://doi.org/10.1016/j.chiabu.2021.105065
          name: "Identifying treatment moderators of a trauma-informed parenting intervention with children in foster care: Using model-based recursive partitioning"

        - authors: __Gerard Chung__, Todd Jensen, Anna Parisi, Rebecca Macy, Paul Lanier
          blog_link: ''
          code_link: ''
          dest: Violence Against Women Journal
          link: https://doi.org/10.1177/1077801220985125
          name: "Impact of Intimate Partner Violence on Parenting and Children’s Behaviors: Transactional Processes Over Time"
    
      year: 2021 
      
    - paper:
        - authors: __Gerard Chung__, Paul Lanier, Peace Wong
          blog_link: ''
          code_link: ''
          dest: Journal of Family Violence
          link: https://doi.org/10.1007/s10896-020-00200-1
          name: "Mediating Effects of Parental Stress on Harsh Parenting and Parent-Child Relationship during Coronavirus (COVID-19) Pandemic in Singapore"
    
        - authors: __Gerard Chung__, Quinton Smith, Joseph Frey, Paul Lanier
          blog_link: ''
          code_link: ''
          dest: Child and Youth Service Review
          link: https://doi.org/10.1016/j.childyouth.2020.105758
          name: "Associations between depression and parenting of fathers in Head Start and parental self-efficacy as a protective factor"
      year: 2020 
    
    - paper:
        - authors: __Gerard Chung__, Carys Chen Xi Wen, Paul Lanier, Peace Wong
          blog_link: ''
          code_link: ''
          dest: Community, Work, and Family Journal (Under review)
          link: https://doi.org/10.31219/osf.io/nz9s8
          name: "Associations Between Work-Family Balance, Parenting Stress, and Marital Conflicts During COVID-19 Pandemic in Singapore"
      year: Preprints


 #  - paper:
 #      - authors: Caroll Comes, __Hadi Sinaee__
 #        blog_link: ''
 #        code_link: https://thecoderepo.com
 #        dest: Udo Madhu Journal
 #        link: https://mypaperishere.com
 #        name: Feugiat sed lectus vestibulum mattis ullamcorper velit sed
 #      - authors: 'Les Larkins, Ana Alvardo, __Hadi Sinaee__ '
 #        blog_link: https://myblogaboutit.com
 #        code_link: ''
 #        dest: Zorka Vita Conference
 #        link: https://mypaperishere.com
 #        name: Venenatis urna cursus eget nunc. Nam aliquam sem et tortor consequat
 #          id porta nibh venenatis
 #      - authors: Les Larkins, __Hadi Sinaee__, Ana Alvardo
 #        blog_link: ''
 #        code_link: ''
 #        dest: Lena Randa Conference
 #        link: https://mypaperishere.com
 #        name: Aliquet eget sit amet tellus cras adipiscing enim eu turpis
 #      - authors: __Hadi Sinaee__, Caroll Comes
 #        blog_link: ''
 #        code_link: ''
 #        dest: Thandeka Radhika Conference
 #        link: ''
 #        name: Orci eu lobortis elementum nibh tellus molestie nunc non blandit
 #    year: '2019'
  social:
    - icon: github
      name: GitHub
      url: https://github.com/gerardchung 
    - icon: twitter
      name: Twitter
      url: https://twitter.com/GerardChung
    - icon: graduation-cap
      icon_pack: fas
      link: https://scholar.google.com/citations?user=9aeYOx8AAAAJ&hl=en
    - icon: researchgate
      icon_pack: fab
      link: https://www.researchgate.net/profile/Gerard_Chung
  subtitle: Social Work Researcher
